version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  service1:
    build: ./service1
    ports:
      - "8081:8080"

  service2:
    build: ./service2
    ports:
      - "8082:8080"

  service3:
    build: ./service3
    ports:
      - "8083:8080"

  service4:
    build: ./service4
    ports:
      - "8084:8080"

  service5:
    build: ./service5
    ports:
      - "8085:8080"
